
    import Head from "next/head";
    import Bread3 from "./bread3";
    import Footer from "../footer";
    import ResponsiveCarousel from "./Responsive";
    import styles from '/styles/Home.module.css'
    import { useState, useEffect } from 'react'
    

    export default function Home() {

      const [ idioma, setIdioma] = useState ("English")  
      const [ titulo, setTitulo] = useState ("KNOW THE COMPANIES LISTED ON THE COLOMBIAN STOCK EXCHANGE")  



      useEffect(()=> {
            
        if ( idioma == "English") {
  
          setTitulo("KNOW THE COMPANIES LISTED ON THE COLOMBIAN STOCK EXCHANGE")
  
        } else {
  
          setTitulo("CONOCE LAS EMPRESAS QUE COTIZAN EN LA BOLSA COLOMBIANA")

        }
        
        
         
      }) 

      return (
        <div>
          <Head>
            <title>Next.js Carousels</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
            <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed&family=Bellefair&family=DM+Sans:wght@500&family=Delicious+Handrawn&family=Inter:wght@200;600;700;900&family=League+Spartan:wght@900&family=Roboto+Condensed&family=Rubik&display=swap" rel="stylesheet"/>
            <script src="https://kit.fontawesome.com/068ec41cf0.js" crossorigin="anonymous"></script>
          </Head>
          <main className={styles.main}>
            <Bread3 lenguague={setIdioma} /> {/* aqui estoy recibiendo la prop y enviandola directamente al setIdioma, tambien se pueden enviar a functions o const */}
            <h1>{titulo}</h1>
            <ResponsiveCarousel idioma={idioma} />
          </main>
          <div className={styles.footerempre}>
            < Footer idioma={idioma} />    
           </div>   
        </div>
      );
    }