import styles from '/styles/Home.module.css'
import React from 'react'



export default function Edu3() {
    return (
        <>
         <div className={styles.edutext}>
             <h1>Análisis Técnico</h1>
             <img className={styles.imgedu} src="/edu31.jpg" alt="edu31" />
             <p>Y llegó la hora del análisis técnico. Como hablamos en los anteriores apartados, cuando yo voy a elegir donde canalizar mi inversión en bolsa (centrándonos en el tema de acciones), existen dos herramientas principales: Análisis fundamental (tratado anteriormente) y el análisis técnico.</p>
             <h2>¿De qué se trata el análisis técnico?</h2>
             <p>Simple y sencillamente es el estudio de gráficas. El analista técnico es aquel que mediante el estudio de la cotización histórica que ha dejado el activo, intenta predecir, cuál va a ser su comportamiento futuro. Es decir, cuando invertimos mediante esta herramienta, lo que hacemos es estudiar cómo se ha comportado el precio histórico de nuestra acción, para luego invertir nuestro dinero, intentando prever para donde se seguirá moviendo el precio.</p>
             <h2>Características del análisis técnico</h2>
             <img className={styles.imgedu} src="/edu32.jpg" alt="edu32" />
             <p>Vayamos un poco más al detalle…</p>
             <p><span>La cotización del activo resume todo lo que se necesita saber.</span>Los analistas técnicos son grandes defensores de su trabajo. Para ellos, en el mundo bursátil, existe mucha información privilegiada a cerca de las empresas y todos los aspectos que pueden afectar su valor en bolsa, que no conoce el público general. Por ello, los técnicos sustentan que los que si acceden a esta información privilegiada, la utilizan para su bien antes de que salga a ser conocida por el público, y por tanto, cuando finalmente se conoce la información, esta ya ha sido descontada en el precio que tiene la acción en bolsa. De esta manera sostienen, <span>que más que analizar los fundamentales de una empresa, un inversionista o trader, debe es analizar cómo se mueve el precio de la acción en bolsa como su verdadera fuente de información.</span></p>
             <p><span>Maneja menor información que el análisis fundamental. </span>Aunque claramente, para llegar a tener un nivel de análisis técnico satisfactorio se necesita de mucha preparación y experiencia operativa, también es cierto, que el análisis técnico busca “facilitarle” la toma de decisiones al inversionista. Es decir, <span>busca que cada uno de nosotros desarrollemos una estrategia sencilla y exitosa basada únicamente en el análisis de gráfica.</span>Algo que difiere con el análisis fundamental, puesto que este último requiere de un nivel investigativo de mayor profundidad.</p>
             <p><span>La tendencia es tu amiga. </span>Los precios de las acciones se mueven en tendencias. Es decir, un tiempo suben, bajan, y otro tanto se mantiene en un movimiento lateral. El análisis técnico nos ofrece a nosotros como inversionistas, herramientas para ir con dichos movimientos. No hay nada más desastroso para un dinero invertido, que apostarle a el lado contrario al que se dirige el mercado.</p>
             <p><span>El Stop Loss es la regla número 1.  </span>El stop loss (freno de la pérdida) es una herramienta de gran ayuda para cualquier inversionista, Se basa en algo sencillo, si nosotros estamos equivocados en nuestro análisis, y el mercado no lo demuestra así con el movimiento del precio de nuestra acción, nuestro deber es salir inmediatamente de esa inversión. Como el análisis técnico se basa exclusivamente en gráficas y no pretende introducir fundamentales a su estrategia de inversión, muy fácilmente podemos quedar “ciegos” ante una noticia muy importante que afecte el precio de nuestra inversión. Por tanto, teniendo en claro lo anterior, siempre es importante cuidar nuestro capital de las inversiones perdedoras, vendiendo dicha inversión, cuando así se requiere.</p>
             <p><span>Manejo de las emociones.  </span>Uno de los aspectos que más cuesta desarrollar en nuestra vida como inversionistas es el manejo de las emociones. Este es un factor decisivo para llegar al éxito en este negocio. Cuesta tiempo, experiencia (¡y si, dinero!!) aprender a cerrar una inversión perdedora, o suprimir la codicia de una ganadora. ¡Pero una vez se aprende a manejar este aspecto, habremos dado un paso gigantesco!</p>
             <img className={styles.imgedu} src="/edu33.jpg" alt="edu33" />
             <h2>HERRAMIENTAS DE ANÁLISIS TÉCNICO</h2>
             <p>En el mundo del análisis técnico, existen muchas herramientas (indicadores, gráficos, osciladores), que a partir del movimiento del precio y el volumen de negociación de la acción principalmente, tratan de predecir hacia donde se moverá la misma. Veamos uno de ellos:</p>
             <h2>VELAS JAPONESAS</h2>
             <p>¿Qué son?</p>
             <p>Las velas japonesas fueron una herramienta de análisis que utilizaban los japoneses para tratar de predecir cuál sería el precio futuro de los bienes que producían en sus cosechas agrícolas.</p>
             <p>¿Cómo se forma una vela japonesa?. Veamos esto con el siguiente ejemplo:</p>
             <img className={styles.imgedu} src="/edu34.jpg" alt="edu34" />
             <p>Observemos la gráfica superior y centrémonos por un momento en la primera vela, es decir, en la barra de color verde que se encuentra en la parte superior derecha. Supongamos que esa vela representa el movimiento del día de hoy de la acción de Ecopetrol.</p>
             <p><span>¿Cómo se formó esa vela verde? </span>Es sencillo. La vela se divide en dos partes, el cuerpo y la sombra. El cuerpo sería la barra verde, y la sombre, las “paticas” de color negro que se desprenden arriba y abajo del cuerpo verde.</p>
             <p>El cuerpo nos representa lo que varió la acción de Ecopetrol en el día. Para este ejemplo, podemos inferir que la acción empezó a un precio de 4.800 y cerró el dia en 5.100. Si observamos la gráfica, efectivamente ese es el espacio que comprende el cuerpo verde de la vela. Por otro lado, la sombra o las paticas nos muestran precios que alcanzó la acción durante el día pero que no se encuentran dentro de su variación absoluta. En nuestro ejemplo, vemos que la patica o sobra inferior toma un valor de 4.600, esto quiere decir, que muy seguramente la acción de Ecopetrol, arrancó el día a 4.800 y luego bajó a 4,600, para finalmente cerrar a 5.100. Como vemos la acción arrancó a 4.800 y cerró a 5.100, pero en el día alcanzó a cotizar a un precio mínimo de 4,600, el cual es el que representa la sombra o patica inferior.</p>
             <p>Con la sombra superior es algo muy similar. Seguramente en algún momento del día la acción de Ecopetrol alcanzó a cotizar a un precio de 5.200 pero luego se devolvió un poco y cerró en el ya mencionado 5.100. Es decir, la patica superior nos muestra el precio máximo que alcanzó la acción, y la inferior el precio mínimo. Muy sencillo.</p>
             <p>Ahora bien, cuando una acción cierra alza (aumentó de precio) su cuerpo es verde como en el anterior ejemplo. Pero cuando esta cierra a la baja (baja el precio) su cuerpo se torna de color rojo. En las velas rojas las sombras representan lo mismo, simplemente cambian en sentido que nos dicen si el preció cerró más arriba o más abajo del precio inicial.</p>
             <h2>¿Para qué nos sirven las velas japonesas?</h2>
             <p>Las velas nos tratan de ilustrar cual es el sentimiento o hacia donde está la fuerza del mercado. Nos dibujan si la acción de acuerdo a como se movió tiene más probabilidad de subir o de bajar para los siguientes días.</p>
             <p><span>Veamos un momento la vela verde de la parte inferior izquierda.</span> Como podemos ver esta vela es alcista (cuerpo verde) y no tiene sombra superior. Es decir, el precio máximo del día es también el precio al que cerró la acción. Esta vela también tiene una larga sombra inferior, es decir, la acción estuvo cotizando durante el día a la baja, pero finalmente terminó subiendo y cerró en su precio más alto. SI leemos bien lo anterior, notaremos que esta es una vela de gran fuerza alcista, es decir, una vela que nos indica que probablemente el precio en el siguiente día va a ser alcista de nuevo, debido a que la acción cerró en su precio máximo y tiene una larga sombra inferior que la acción pudo resolver, incrementando su precio durante el día.</p>
             <p><span>La vela de la derecha es similar en formación</span>, sino que expresa es una fuerza bajista (espero que sepan inferir el por qué, de lo contrario los invito a leer el anterior análisis y hacer lo mismo con esta vela roja).</p>
             <p><span>La tercera vela es una vela de indecisión</span>. Como podemos ver, el cuerpo de la vela es verde (la acción subió) pero es un cuerpo muy pequeño, la variación de precio fue mínima. En cambio, esta vela si tiene una larga sombra superior e inferior. Lo cual nos quiere decir que el mercado está confundido y no sabe si la acción deba subir o bajar.</p>
             <p>Esto es sólo un abrebocas. Existen muchos tipos de vela y combinación de las mismas. Los invito gustosamente a profundizar en el tema.</p>        
             <img className={styles.imgedu} src="/edu35.jpg" alt="edu35" />
         </div>          
        </>
    )
}