import styles from '/styles/Home.module.css'
import React from 'react'



export default function Edu1() {
    return (
        <>
         <div className={styles.edutext}>
             <h1>¿Qué es esto de la Bolsa de valores?</h1>
             <p>Una Bolsa de Valores, es una organización privada, que funciona fundamentalmente como cualquier otro mercado que nosotros conozcamos. Es decir, existen unos oferentes (vendedores) y unos demandantes (compradores), los cuales compran y venden en un espacio generado para este fin (La Bolsa de Valores). </p>
             <p>Al igual que una familia (demandantes) compra sus víveres de un conjunto de empresas (oferentes) en un supermercado (espacio generado) funciona nuestro mercado de valores, con la diferencia, que en este último, interactúan son los inversionistas, las empresas, el Estado, y la Bolsa de Valores, esta ultima facilitando  los mecanismo para que se negocien los activos financieros (como las acciones), en lugar de víveres como sucede en un supermercado.</p>
             <img className={styles.imgedu} src="/edu11.jpg" alt="edu11" />
             <h1>¿Qué son los activos financieros, y cuales se negocian en la Bolsa de Valores?</h1>
             <p>Un activo financiero es el nombre con el que son conocidos en bolsa, los títulos valores. Es decir, cuando nosotros compramos un titulo valor como las acciones, a través de la bolsa de valores, estamos haciendo una inversión de nuestro dinero, sobre un titulo valor, el cual es representado por un documento o papel que posee un valor, y sobre el cual, esperamos obtener una rentabilidad o ganancia. </p>
             <p>En la bolsa de valores, nosotros podemos invertir o comprar, principalmente en los siguientes activos financieros:</p>
             <p><span>Acciones:</span> Representan un porción o participación propietaria sobre el organismo que las emite. Es decir, cuando compramos acciones, lo que estamos haciendo es invertir nuestro dinero, adquiriendo un pedazo de la compañía en la cual invertimos. Nos hacemos dueños de una parte de esa compañía</p>
             <p>Cuando yo compro una acción, lo hago a un determinado precio, y en la medida que ese precio se incremente, mi rentabilidad será mayor. Por ejemplo, supongamos que yo poseo 5 millones de pesos y deseo invertirlos en acciones de Ecopetrol las cuales se encuentran a 4.000 pesos cada una, es decir, yo estaría comprando 1.250 acciones de esa empresa. Si al cabo de 3 meses, el precio de la acción subió hasta alcanzar los 5.000 pesos y yo quiero vender mis acciones, recibiría 6.250.000 pesos, es decir, tendría una ganancia de 1.250.000 pesos. Sin embargo, es importante conocer que el precio de la acción también puede bajar. Este es el motivo por el cual las acciones son conocidas como inversiones en renta variable, por que el precio de las mismas puede bajar o subir, es decir, mi rentabilidad varía con el movimiento del precio de la acción que posea.</p>
             <p><span>Bonos y Tes: </span> Estos son instrumentos de renta fija. Cuando nosotros queremos invertir nuestro dinero, pero sabemos que no nos gusta mucho el riesgo como en la inversión en acciones, sino que buscamos obtener una ganancia “segura”, la podemos lograr mediante este tipo de inversiones en renta fija.  Los Bonos y los Tes son títulos valores que representan deuda, los primeros son emitidos por empresas y los segundos por los Estados. Es decir, Cuando yo invierto mi dinero en un Bono, lo que estoy haciendo es prestarle dinero a una empresa inscrita en la Bolsa de Valores, y cuando mi inversión es sobre un Tes, también estoy prestando mi dinero, pero esta vez, al Estado. </p>
             <p>Tanto en los Bonos como en los Tes, al momento de invertir mi dinero, se establece la rentabilidad de la inversión de antemano. Es decir, a nosotros como inversionistas nos dan una tasa de rentabilidad sobre la inversión que estamos haciendo. Sin embargo existen dos aspectos importantes a considerar en estas inversiones. Por un lado, estos títulos valores tienen una fecha de vencimiento, es decir, cuando compro un Bono y le presto el dinero a una empresa, dicha empresa me ofrece una tasa o ganancia por mi dinero en una fecha futura, por tanto, a mi me pagan cuando se vence dicho titulo valor o deuda. Si yo quiero venderlo antes, la rentabilidad varía un poco de acuerdo a las condiciones del mercado. Por otro lado estas inversiones no están 100% libres de riesgo. Es posible, aunque poco sucede, que la empresa, o el Estado si invierto en un Tes, se quiebre, ocasionando que la devolución de mi dinero se vea comprometida. Esto sucede muy poco pero es importante tenerlo presente, buscando invertir en empresas con trayectoria y buenos estados financieros.</p>
             <img className={styles.imgedu} src="/edu12.jpg" alt="edu12" />
             <h1>¿De acuerdo a lo anterior, para qué sirve una Bolsa de Valores y que ventajas trae para mí invertir en ella?</h1>
             <p>La Bolsa de Valores es sencillamente un mecanismo  que se fundamenta en  la canalización de recursos para impulsar el crecimiento y desarrollo económico de un país o región. Mediante la Bolsa de Valores, se cumplen  2 fines principales:</p>
             <ol>
                <li>Permite que millones de personas que planean o poseen unos  ahorros, puedan invertir ese dinero, comprando o prestándole a las empresas más grandes e importantes del país, logrando de esa forma ser participes de sus ganancias, viendo crecer su dinero al ritmo de la economía de la nación.</li>
                <li>Permite que las empresas del país o de la región, puedan financiarse, es decir, obtener el dinero que necesitan para crecer, a través del publico en general, logrando suplir esta necesidad mediante mecanismos diferentes a los tradicionales (prestamos bancarios).</li>
             </ol>
             <p>La siguiente gráfica ilustra las ventajas que puede traer para mí como inversionista, el invertir mi dinero a través de la Bolsa de valores:</p>
             <img className={styles.imgedu} src="/edu13.jpg" alt="edu13" />
             <h1>¿Cómo compro y vendo en el mercado de valores?</h1>
             <p>Si llegado el momento, tenemos una platica ahorrada, que no queremos tener en una cuenta bancaria u otro producto similar, sino que queremos invertirla a través de la bolsa, el proceso es muy sencillo. Para comprar  activos como las acciones, simplemente nos debemos acercar a una comisionista de bolsa.</p>
             <p>Las comisionistas de bolsa, son instituciones inscritas en la bolsa de valores, para acercar a los inversionistas con las empresas. Es decir, mediante estas comisionistas es que yo puedo comprar y vender títulos valores como las acciones. </p>
             <p>En nuestra Bolsa de Valores de Colombia (BVC) tenemos alrededor de 10 firmas comisionistas avaladas. Es muy fácil encontrarlas en las principales ciudades, aunque si usted no vive en una de ellas no se preocupe, fácilmente por teléfono o por correo se puede contactar a una de ellas. Aunque no se recibe una asesoría en persona, cualquier  inversionista, luego de consignar su dinero en la comisionista de su confianza (proceso serio y seguro), puede recibir instrucciones sobre en que activos invertir, y también puede dar la orden de por teléfono e incluso, por correo electrónico.</p>
             <p>Las comisionistas de bolsa, cobran un porcentaje o comisión sobre cada operación. Por ejemplo, si yo poseo 10 millones de peso para invertir, deseo comprar acciones, y mi comisionista me sugiere que compremos títulos de Bancolombia, ellos me cobran una comisión sobre el monto de operación. Es decir, si la comisión es del 1% (porcentaje que varía de acuerdo a cada comisionista), al momento de comprar, me descuentan ese valor , 100.000 pesos,  y otro 1% al momento de vender.</p>
             <p>¿Les parece muy caras las comisiones? También existe una solución para eso, El E-trading.  El porcentaje que cobran las comisionistas, incluye la operación de compra o venta, y la asesoría para escoger lo mejor posible entre las opciones. Por otro lado, si nosotros consideramos que conocemos sobre el mercado, y podemos tomar nuestras propias decisiones sin asesoría profesional, podemos comprar y vender acciones mediante el E-trading.  </p>
             <p>E-trading es la compra y venta de activos por plataformas conectadas a través de internet. Es decir, si yo lo deseo así, la comisionista de bolsa me deja acceder a un programa o plataforma, en donde a partir de una conexión a internet, yo puedo comprar y vender directamente desde mi casa o lugar de trabajo. Este es un proceso muy sencillo, y económico, puesto que las comisiones que se manejan, son considerablemente mas bajas. Por supuesto, quiero recalcar que se recomienda seriamente el tener conocimientos y experiencia en el tema.</p>
             <h1>¿Cómo compro y vendo en el mercado de valores?</h1>
             <p>Una vez hemos decidido invertir nuestros ahorros en el mercado accionario, o nos queremos preparar para el momento en que podamos hacerlo, es necesario para cualquier inversionista, aún cuando cuente con asesoría profesional y personalizada, conocer cuales son los métodos más utilizados en el análisis de este tipo de  inversiones, los cuales nos ayudarán a crear una estrategia efectiva,  en sentido de maximizar nuestras ganancias. </p>
             <p>Existen dos grandes “escuelas”  utilizadas para determinar este objetivo. El <span>análisis fundamental</span> y el <span>análisis técnico</span>. Estos van a ser nuestros guías en este camino de hacer de nuestra inversión en bolsa, una experiencia satisfactoria, que a futuro, nos lleve a ser unos inversionistas rentables y exitosos. Estas dos escuelas, van a ser nuestro próximo tema en secuencia.</p>
             <h2>“Aquel que no es suficientemente fuerte como para correr riesgos, no podrá lograr nada en la vida”<span>(Muhammad Ali)</span></h2>
         </div>          
        </>
    )
}